/**:
  ros__parameters:
    # plugin_denylist:
      
      # # common
      # - 3dr_radio
      # # - actuator_control
      # - hil
      # - ftp
      # - manual_control
      # - safety_area
      # - setpoint_accel
      # - setpoint_velocity
      # - setpoint_position
      # - setpoint_attitude
      # - setpoint_trajectory
      # - home_position
      # - sys_time
      # - vfr_hud
      # - waypoint
      # - landing_target
      # - mount_control
      # - onboard_computer_status
      
      # # extras
      # - image_pub
      # - vibration
      # # - distance_sensor
      # - rangefinder
      # - vision_speed_estimate
      # - vision_pose_estimate
      # - px4flow
      # - mocap_pose_estimate
      # - cam_imu_sync
      # - fake_gps
      # # - gps_rtk
      # - obstacle_distance
      # - servo_state_publisher
      # - companion_process_status
      # - wheel_odometry
      # - trajectory
      # # - odom
      # - adsb
      # # - debug_value
      # - wind_estimation
      # - log_transfer

    plugin_allowlist:
      # core
      # - actuator_control
      - altitude
      - attitude
      - command
      - global_position
      - home_position
      - imu
      - local_position
      - manual_control
      # - param
      # - rc_io
      - setpoint_accel
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_velocity
      - sys_status
      - sys_time

      # mavros_extras
      - distance_sensor
      - gps_input
      - gps_rtk
      # - gps_status
      - mag_calibration_status
      - odometry
