hw_interface_plugin: "mrs_uav_px4_api/Api"

mavros_timeout: 1.0 # [s]

simulated_rtk:
  utm_zone: "32T"
  utm_x: 465710.758973
  utm_y: 5249465.43086
  amsl: 340.0

motor_speeds:
  num_motors: 4
  motor_slowdown_constant: 0.0159236 # used only in simualation

inputs:
  control_group: false
  attitude_rate: true
  attitude:      true

outputs:
  distance_sensor:      true
  gnss:                 true
  rtk:                  true
  imu:                  true
  altitude:             true
  magnetometer_heading: true
  magnetic_field:       true
  rc_channels:          true
  battery_state:        true
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             true
  ground_truth:         true
