hw_interface_plugin: "mrs_uav_px4_api::MrsUavPx4Api"
plugin:

  mavros_timeout: 1.0 # [s]
  mavros_passable_delay: 0.05 # [s]
  
  gnss:
    utm_zone: "32T"
    utm_x: 465710.758973
    utm_y: 5249465.43086
    amsl: 340.0
  
  input_mode:
    control_group: false
    attitude_rate: true
    attitude:      true
  
  outputs:
    distance_sensor:      true
    gnss:                 true
    gnss_status:          true
    rtk:                  false # TODO implement RTK
    imu:                  true
    altitude:             true
    magnetometer_heading: true
    magnetic_field:       true
    rc_channels:          true
    battery_state:        true
    position:             true
    orientation:          true
    velocity:             true
    angular_velocity:     true
    odometry:             true
    ground_truth:         true
